#Reversed integer

Вам дано число целого типа ``a``. Вам необходимо написать функцию, которая принимает это число на вход, а на выход выдает целое число, цифры в котором записаны в обратном порядке.


**Sample Input 1:**

``
a = 123
``

**Sample Output 1:**

``321``

**Sample Input 2:**

``
a = 120
``

**Sample Output 2:**

``21``

**Sample Input 3:**

``
-123
``

**Sample Output 3:**

``321``

In [138]:
def reverse_number(a: int):
    try:
        plus_minus = a/abs(a)
        a_str = str(abs(a))
        a_str_reverse = a_str[::-1]
        a_reverse = int(a_str_reverse)
        return int(a_reverse * plus_minus)
    except:
        return 'Введен неправильный параметр'

print(reverse_number(123))
print(reverse_number(120))
print(reverse_number(-123))
print(reverse_number(120.57))




321
21
-321
Введен неправильный параметр


Напишите функцию, которая принимает единственное число ``n: int``. Это число определяет длину стороны квадрата. Функция должна нарисовать квадрат из звездочек, при этом звездочки должны быть только на ребрах квадрата, центр должен быть выколот.

**Sample Input 1:**

``
n = 5
``

**Sample Output 1:**
```
* * * * *
*       *
*       *
*       *
* * * * *

```

In [139]:
def square(a):
    for i in range(a):
        str_=''
        for j in range(a):
            condition_ = (i == 0) or (i == a-1) or (j == 0) or (j == a-1)
            if condition_:
                str_ += '*  '
            else:
                str_ += '   '
        print(str_)

square(7)

*  *  *  *  *  *  *  
*                 *  
*                 *  
*                 *  
*                 *  
*                 *  
*  *  *  *  *  *  *  


#Пермутации

Вам дан массив с целыми числами ``nums``. Напишите функцию, которая принимает на вход данный массив и возвращает все возможные пермутации с данными числами. Возвращать массивы можно в любом порядке.

**Sample Input 1:**

``
nums = [1,2,3]
``

**Sample Output 1:**

``[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]``

**Sample Input 2:**

``
nums = [0,1]
``

**Sample Output 2:**

``[[0,1],[1,0]]``

**Sample Input 3:**

``
nums = [1]
``

**Sample Output 3:**

``[[1]]``

In [140]:
# вариант 1
import itertools

def permutations(a):
    l = list(itertools.permutations(a))
    perm_ = [list(x) for x in l]
    return perm_

print(permutations([1, 2, 3]))
print(permutations([1]))

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]
[[1]]


In [141]:
# вариант 2
import math
import numpy as np

def permutations2(a):
    length = len(a)
    variants_amount = math.factorial(length)

    j = 0
    perm1 = []

    for i in range(variants_amount):
        b = a.copy()
        perm1.append(b)

        if j < length - 1:
            a[j],a[j+1] = a[j+1], a[j]
        else:
            a[j], a[0] = a[0], a[j]

        j = j+1 if j < length-1 else 0

    return perm1
        
print(permutations2([1, 2, 3]))
print(permutations2([1]))

[[1, 2, 3], [2, 1, 3], [2, 3, 1], [1, 3, 2], [3, 1, 2], [3, 2, 1]]
[[1]]


### Почти двойной факториал
Дано натуральное $N \leqslant 100$.  Выведите произведение всех чётных натуральных чисел, не превосходящих $N$.

In [142]:
from numpy import double


def almost_double_factorial(n):
    f = 1
    for i in range(1,n+1):
        if i%2 == 0:
            f *= i
    return f

N = 25
#YOUR CODE
N_double_fact = almost_double_factorial(N)
print(N_double_fact)

assert N_double_fact == 1961990553600, "Something is wrong! Please try again"

N = 100
N_double_fact = almost_double_factorial(N)
assert N_double_fact == 34243224702511976248246432895208185975118675053719198827915654463488000000000000, "Something is wrong! Please try again"

1961990553600


### Хитрая сортировка

Пусть у нас есть следующий список, в котором элементы -- tuple из строк:

``items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]``

Мы хотим отсортировать этот список по последней букве второго элемента каждого ``tuple``, т.е. получить такой список:

``sorted_items = [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')]``.
Что нужно вставить вместо "###" в следующем выражении, чтобы получить сортировку?

``sorted_items = sorted(items, key=lambda x: ###)``

In [143]:
items = [('one', 'two'), ('three', 'four'), ('five', 'six'), ('string', 'a')]

sorted_items = sorted(items, key=lambda x: x[1][-1])
                      
assert sorted_items == [('string', 'a'), ('one', 'two'), ('three', 'four'), ('five', 'six')], \
"Something is wrong! Please try again"

### Еще строки

Вашей программе на вход подаются три строки ``s, a, b``, состоящие из строчных латинских букв.
За одну операцию вы можете заменить все вхождения строки ``a`` в строку ``s`` на строку ``b``.

Например, ``s = "abab", a = "ab", b = "ba"``, тогда после выполнения одной операции строка ``s`` перейдет в строку ``"baba"``, после выполнения двух и операций – в строку ``"bbaa"``, и дальнейшие операции не будут изменять строку ``s``.

Необходимо узнать, после какого минимального количества операций в строке ``s`` не останется вхождений строки ``a``. Если операций потребуется более 1000, выведите ``Impossible``.

Выведите одно число – минимальное число операций, после применения которых в строке ``s`` не останется вхождений строки ``a``, или ``Impossible``, если операций потребуется более 1000.

**Sample Input 1:**

``
ababa
a
b
``

**Sample Output 1:**

``1``

**Sample Input 2:**

``ababa
b
a``

**Sample Output 2:**

``1``

**Sample Input 3:**

``ababa
c
c``

**Sample Output 3:**

``0``

**Sample Input 4:**

``ababac
c
c``

**Sample Output 4:**

``Impossible``


In [144]:
def my_func(s,a,b):
    i = 0
    if a == b: 
        return('Impossible')
    while True:
        s1 = s.replace(a,b)
        if s1 == s:
            break
        else:
            i += 1
            s = s1
            if i > 1000:
                return ('Impossible')
    #YOUR CODE
    return i

print(my_func('abababa', 'ab', 'ba'))
print(my_func('abababa', 'a', 'b'))
print(my_func('abababa', 'd', 'd'))

s3 = 'abababab'
for x in range (10):
    s3+=s3
print(my_func(s3, 'ab', 'ba'))

3
1
Impossible
Impossible


### Создание массивов
Дан массив $A[0,\ldots,N-1]$. Напишите функцию, принимающую один обязательный аргумент A и один опциональный аргумент ``erase``, по умолчанию равный 1. Возвратите массив $B[0,\ldots, N-1]$, где $B_i = A_0 + \ldots + A_{i}$ --- массив частичных сумм массива $A$, предварительно удалив из массива $B$ все элементы, равные erase. Постарайтесь сделать это за линейное время без использования Numpy.

In [145]:
def cumsum_and_erase(A, erase=1):
    B = []
    s = 0
    for a in A:
        s += a
        B.append(s)

    try:
        while True:
            B.remove(erase)
    except:
        return B

A = [5, 1, 4, 5, 14]
B = cumsum_and_erase(A, erase=10)

assert B == [5, 6, 15, 29], "Something is wrong! Please try again"

### Обработка текста
Дан список текстов, слова в которых разделены пробелами (можно считать, что знаков препинания нет). Часть слов является "мусорными": в них присутствуют цифры и спецсимволы. Отфильтруйте такие слова из каждого текста. Используйте функции ``str.split``, ``str.isalpha``, ``str.join``, а также [генератор filter](http://pythonicway.com/python-functinal-programming).

In [146]:
sentences = ['1 thousand devils', 'My name is 9Pasha', 'Room #125 costs $100']

def process(sentences):
    result = []
    for sentence in sentences:
        words = sentence.split()
        new_words = []
        for word in words:
            if word.isalpha():
                new_words.append(word)
            new_sentence = ' '.join(new_words)
        result.append(new_sentence)
    
    return result

assert process(sentences) == ['thousand devils', 'My name is', 'Room costs'], \
"Something is wrong! Please try again"

#Расстояние Хэмминга

Вам даны две строки, ``a`` и ``b`` одинаковой длины. Необходимо посчитать расстояние Хэмминга между ними, которое определяется как количество символов, которые не совпадают между двумя строками в одинаковой позиции.

**Sample Input 1:**

```
a = 'AGCT'
b = 'ACGT'
hamming(a, b)
```

**Sample Output 1:**

``2``

In [147]:
#вариант 1

def hamming_distance(a,b):
    counter = 0
    for i in range(len(a)):
        if a[i] != b[i]:
            counter += 1
    return counter

a = 'AGCT'
b = 'ACGT'
hamming_distance(a,b)

2

In [148]:
# вариант 2

def hamming_distance2(x, y):
    from scipy.spatial.distance import hamming    
    return(int(hamming(list(x),list(y)) * len(x)))

a = 'AGCT'
b = 'ACGT'

hamming_distance2(a, b)

2

In [149]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [150]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.55418758 0.49873482 0.27760181 ... 0.52352488 0.37797537 0.13589479]
 [0.5850923  0.44421771 0.82687115 ... 0.30896647 0.16081922 0.3550787 ]
 [0.05421762 0.15279888 0.26625629 ... 0.77422738 0.56674739 0.97056437]
 ...
 [0.38210754 0.79323941 0.30216046 ... 0.40525183 0.34688484 0.74349589]
 [0.17843169 0.20516674 0.77147754 ... 0.35518282 0.54765086 0.23516361]
 [0.67148754 0.8914312  0.92123753 ... 0.37991698 0.91847242 0.89631718]]
[[0.15566273 0.43905531 0.1174226  ... 0.71668446 0.00445498 0.18707718]
 [0.29170479 0.69023876 0.48394637 ... 0.02493352 0.30849277 0.09585877]
 [0.84217853 0.71220186 0.71843302 ... 0.99529777 0.90608823 0.72401978]
 ...
 [0.05786956 0.4333151  0.68939748 ... 0.86168342 0.26289719 0.93610153]
 [0.35496689 0.95875614 0.92671161 ... 0.42904197 0.94583014 0.36829932]
 [0.73519843 0.92884101 0.32148408 ... 0.85012788 0.8686105  0.44867655]]


In [156]:
def mult(a, b):
    
    result =[]
    for i in range(len(a)):
        r = []
        for j in range(len(b[0])):
            r.append(0)
        result.append(r)

    for m in range(len(a)): 
        for n in range(len(b[0])): 
            for o in range(len(b)): 
                result[m][n] += a[m][o] * b[o][n]

    return result
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy (может помочь функция zip)
    """

In [152]:
def np_mult(a, b):
    return np.dot(a,b)
    """  
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    pass

In [157]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 1 s
Wall time: 1.04 s


In [154]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 7.98 ms


In [158]:
# проверим корректность
assert np.allclose(np.array(M1), M2)